export const TEMPLATE_INTELLISENSE_FRAMEWORK_LBOS_TOKEN: string = "<TEMPLATE_INTELLISENSE_FRAMEWORK_LBOS_TOKEN>";

export const TEMPLATE_INTELLISENSE_LBOS: string = `
export namespace LBOS {
    ${TEMPLATE_INTELLISENSE_FRAMEWORK_LBOS_TOKEN}
}

`;
